### ISSUE TITLE
Test suite/comparison

### ISSUE THREAD

**Issue by cburgmer** [akshaymankar/jsonpath-hs#2]
Hi Akshay, would you be interested in https://cburgmer.github.io/json-path-comparison/ for providing more test cases? I have started comparing quite a few different implementations already. I'll probably need to spend quite some time to get into Haskell though and thought for now it's easier just to make you aware of the undertaking.

**Comment by akshaymankar** [comment]
Hello @cburgmer, apologies for the late reply, somehow I was not watching my own repository! 
I would be happy to help you add this library to the comparison. Can you please describe what you'd need for that?

**Comment by cburgmer** [comment]
Glad to hear that!
I have a very short description under https://github.com/cburgmer/json-path-comparison#contribute. Let me know if this is enough to start. 
Maybe https://github.com/cburgmer/json-path-comparison/tree/master/implementations/Java_com.jayway.jsonpath is a good candidate to copy from.
