### ISSUE TITLE
Consider removing upper bounds

### ISSUE THREAD

**Issue by MichaelXavier** [akshaymankar/jsonpath-hs#3]
Hi,

I was considering using this for a project but it looks like unordered-containers is out of bounds. I was wondering before I submitted a merge request if you would be amenable to the removal of upper bounds on basic packages like aeson, unordered-containers, text, vector, etc. I find for packages like this that have a pretty well-defined scope you end up having to endlessly bump upper bounds when 95% of the time a version update on these libraries is fine and if it isn't, you'll get a compile-time error that you can work around with CPP or other means. When you remove upper bounds the package can be in a "done" state for years without needing any intervention.

**Comment by akshaymankar** [comment]
This sounds reasonable, I'd be happy to merge a PR and make a revision on hackage to remove upper bounds for these packages.

**Comment by akshaymankar** [comment]
Thanks for the PR, @MichaelXavier!

**Comment by MichaelXavier** [comment]
@akshaymankar thanks for merging! Quick note though, it looks like you added a revision that changed the package bounds on hackage. I think this works for most tools but not for nix, because the tarball that it downloads still has the old bounds. Would it be possible to get a release as well?

**Comment by akshaymankar** [comment]
Ok, I have uploaded v1.0.2 on hackage.

I know very little about nix, but it seems absurd that it doesn't support revisions. I was only uploading revisions because the hackage trustees recommend it [here](https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md#why-not-just-keep-uploading-new-versions).
Are you aware of any efforts to either make nix tooling align with hackage or vice-versa?

**Comment by MichaelXavier** [comment]
Thanks! I'm fairly new to nix. I was only going by what I was observing: I used `callHackageDirect` which downloads the tarball and uses its SHA to avoid redownloading. I think because its a tarball, it wasn't using the revisions but what is actually contained in the file, which seems fairly reasonable because nix is sort of oriented around downloading and caching the inputs and then building packages. I feel like at least in the past stack had problems with revisions too. I'm generally not in favor of them because they seem to let the package and the metadata diverge but I definitely see the appeal of poking the dependencies without doing releases and keeping abandoned packages buildable.
