### ISSUE TITLE
Is it possible to get the key?

### ISSUE THREAD

**Issue by ivanperez-keera** [akshaymankar/jsonpath-hs#46]
Is there an expression I can use to obtain the key? For example, if I have:

```json
{ "key" : "value" }
```

I want to obtain only "key".

**Comment by akshaymankar** [comment]
I think its not directly possible, once you have the `Object` you can get all its keys. Do you have a more complex example for this? 
Also checkout the RFC for JSONPath standardization: https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html. Maybe it gives you some pointers.

**Comment by ivanperez-keera** [comment]
Ok, thanks!
