### ISSUE TITLE
Error installing with `aeson-2.0.2.0`

### ISSUE THREAD

**Issue by ivanperez-keera** [akshaymankar/jsonpath-hs#48]
This library depends on `aeson >= 2`. However the use of `Data.Aeson.KeyMap.elems` requires `aeson >= 2.0.3.0`.

Could that be fixed?

**Comment by akshaymankar** [comment]
Thanks for the report. I published a new revision for 0.3.0.0 on hackage: https://hackage.haskell.org/package/jsonpath-0.3.0.0
