### ISSUE TITLE
Results do not match other implementations

### ISSUE THREAD

**Issue by cburgmer** [akshaymankar/jsonpath-hs#6]
Results do not match other implementations

The following queries provide results that do not match those of other implementations of JSONPath
(compare https://cburgmer.github.io/json-path-comparison/):

- [ ] `$[?@.key==42]`
  Input:
  ```
  [
    {
      "key": 0
    },
    {
      "key": 42
    },
    {
      "key": -1
    },
    {
      "key": 1
    },
    {
      "key": 41
    },
    {
      "key": 43
    },
    {
      "key": 42.0001
    },
    {
      "key": 41.9999
    },
    {
      "key": 100
    },
    {
      "key": "some"
    },
    {
      "key": "42"
    },
    {
      "key": null
    },
    {
      "key": 420
    },
    {
      "key": ""
    },
    {
      "key": {}
    },
    {
      "key": []
    },
    {
      "key": [
        42
      ]
    },
    {
      "key": {
        "key": 42
      }
    },
    {
      "key": {
        "some": 42
      }
    },
    {
      "some": "value"
    }
  ]
  ```
  Expected output:
  ```
  NOT_SUPPORTED
  ```
  Actual output:
  ```
  [
    {
      "key": 42
    }
  ]
  ```

For reference, the output was generated by the program in https://github.com/cburgmer/json-path-comparison/tree/master/implementations/Haskell_jsonpath.

**Comment by schrammc-ebot7** [comment]
A good amount of these is resolved. It might make sense to remove them from the list (or at least mark them as done) in order to better keep track in the future.

**Comment by akshaymankar** [comment]
I ran the report locally by pinning jsonpath to this HEAD of this repo. I have updated the list. I will make a release and update the build in the json-path-comparison repo.

**Comment by schrammc** [comment]
Are we sure this list of cases is correct? We have a unit test for `$[""]` working but the list here says the path doesn't parse.

**Comment by akshaymankar** [comment]
Hmm, looks like ninja is not running some rules again. Let me see if I can convince it to run things.

**Comment by akshaymankar** [comment]
Alright, I have fixed the top comment.

**Comment by akshaymankar** [comment]
With #32 all the old problems got solved and a new one came up. I think its ok if this implementation supports filters without brackets, so I will just leave it and close this issue.

**Comment by glyn** [comment]
> I think its ok if this implementation supports filters without brackets, so I will just leave it and close this issue.

Onlookers please note the [draft IETF spec](https://datatracker.ietf.org/wg/jsonpath/documents/) supports filters without brackets.
